teste

diff --git a/.github/workflows/covarege.yml b/.github/workflows/covarege.yml
--- a/.github/workflows/covarege.yml
+++ b/.github/workflows/covarege.yml
@@ -28,28 +28,21 @@ jobs:
 
     - name: Run PHPUnit tests with coverage
       run: |
-        vendor/bin/phpunit --coverage-text
+        vendor/bin/phpunit --coverage-clover=coverage.xml
+
+    - name: Ensure coverage is above 60%
+      run: |
+        coverage=$(grep 'line-rate' coverage.xml | grep -o '0\.[0-9]*')
+        coverage_percent=$(echo "$coverage * 100" | bc | cut -d'.' -f1)
+        echo "Code Coverage: $coverage_percent%"
+        if [ $coverage_percent -lt 60 ]; then
+          echo "Coverage is below 60%, failing the workflow."
+          exit 1
+        fi
+        echo "Coverage is above 60%, proceeding."
 
     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v3
       with:
         file: coverage.xml
         token: ${{ secrets.CODECOV_TOKEN }}
-
-    - name: Check Codecov Coverage
-      uses: codecov/codecov-action@v3
-      with:
-        file: coverage.xml
-        token: ${{ secrets.CODECOV_TOKEN }}
-      env:
-        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-      continue-on-error: true # Allow to fail without failing the entire workflow
-
-    - name: Ensure coverage is above 60%
-      run: |
-        coverage=$(curl -s https://codecov.io/api/gh/${{ github.repository }}/reports/coverage | jq -r '.total.coverage')
-        if [ $(echo "$coverage < 60" | bc) -eq 1 ]; then
-          echo "Coverage is below 60%, failing the workflow."
-          exit 1
-        fi
-        echo "Coverage is above 60%, proceeding."
